openMF/ph-ee-operations-web

src/app/payment-hub/transactions/transaction-details.component.html, src/app/payment-hub/transactions/transaction-details.component.scss
add colors in status column of transaction task list table.
=> feat: add colors in status column of transaction task list table

src/app/payment-hub/paymenthub.module.ts, src/app/payment-hub/transactions/transaction-details.component.html, src/app/pipes/pipes.module.ts, src/app/pipes/pretty-print.pipe.spec.ts, src/app/pipes/pretty-print.pipe.ts
added pretty print pipe to format json paramter in transaction business attributes.
=> feat: add pipe to format json parameter in transaction business attributes

src/app/payment-hub/paymenthub.module.ts, src/app/payment-hub/transactions/transaction-details.component.html, src/app/payment-hub/transactions/transaction-details.component.scss, src/app/payment-hub/transactions/transaction-details.component.ts, src/app/shared/icons.module.ts
grouped the tasks of transaction task list table.
=> feat: group the tast of transaction task list 

src/app/payment-hub/transactions/transaction-details.component.html, src/app/payment-hub/transactions/transaction-details.component.ts
=> feat: add refund dialog

src/app/payment-hub/paymenthub-routing.module.ts, src/app/payment-hub/paymenthub.component.html, src/app/payment-hub/paymenthub.module.ts, src/app/payment-hub/request-to-pay/common-resolvers/request-to-pay.resolver.ts, src/app/payment-hub/request-to-pay/common-resolvers/view-request-to-pay.resolver.ts, src/app/payment-hub/request-to-pay/helper/date-format.helper.ts, src/app/payment-hub/request-to-pay/helper/request-to-pay.helper.ts, src/app/payment-hub/request-to-pay/incoming-request-to-pay/incoming-request-to-pay.component.html, src/app/payment-hub/request-to-pay/incoming-request-to-pay/incoming-request-to-pay.component.scss, src/app/payment-hub/request-to-pay/incoming-request-to-pay/incoming-request-to-pay.component.spec.ts, src/app/payment-hub/request-to-pay/incoming-request-to-pay/incoming-request-to-pay.component.ts, src/app/payment-hub/request-to-pay/model/currency.model.ts, src/app/payment-hub/request-to-pay/model/dfsp.model.ts, src/app/payment-hub/request-to-pay/outgoing-request-to-pay/outgoing-request-to-pay.component.html, src/app/payment-hub/request-to-pay/outgoing-request-to-pay/outgoing-request-to-pay.component.scss, src/app/payment-hub/request-to-pay/outgoing-request-to-pay/outgoing-request-to-pay.component.spec.ts, src/app/payment-hub/request-to-pay/outgoing-request-to-pay/outgoing-request-to-pay.component.ts, src/app/payment-hub/request-to-pay/service/request-to-pay.service.ts, src/app/payment-hub/request-to-pay/view-request-to-pay/view-request-to-pay.component.html, src/app/payment-hub/request-to-pay/view-request-to-pay/view-request-to-pay.component.scss, src/app/payment-hub/request-to-pay/view-request-to-pay/view-request-to-pay.component.spec.ts, src/app/payment-hub/request-to-pay/view-request-to-pay/view-request-to-pay.component.ts, src/app/payment-hub/transactions/service/transactions.service.ts
add incoming/outgoing request to pay
=> feat: add incoming/outgoing request to pay

src/app/payment-hub/request-to-pay/service/request-to-pay.service.ts, src/app/payment-hub/request-to-pay/view-request-to-pay/view-request-to-pay.component.html, src/app/payment-hub/request-to-pay/view-request-to-pay/view-request-to-pay.component.ts
connected the transaction request to required APIs.
=> feat: connected request to API

src/app/payment-hub/transactions/incoming/incoming-transactions.component.ts, src/app/payment-hub/transactions/outgoing/outgoing-transactions.component.ts
=> fix: removed errors

src/app/payment-hub/transactions/incoming/incoming-transactions.component.html, src/app/payment-hub/transactions/outgoing/outgoing-transactions.component.html
=> fix: completed at date error

src/app/pipes/pretty-print.pipe.ts
modified pipe to print JSON parameter in pretty format.
Screenshots:
=> feat: pretty print JSON parameter

src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.html, src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.ts
@avikganguly01 Please check this PR
=> Updated the export filter

src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.html, src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.ts
@avikganguly01  updated  PR with the Path Fix.
=> Updated path

src/app/payment-hub/paymenthub.component.html, src/app/payment-hub/paymenthub.component.scss, src/app/payment-hub/request-to-pay/bulk-batch-export/bulk-batch-export.component.html, src/app/payment-hub/request-to-pay/bulk-batch-export/bulk-batch-export.component.scss, src/app/payment-hub/request-to-pay/bulk-batch-export/bulk-batch-export.component.ts, src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.html, src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.ts
http://localhost:4200/paymenthubee/bulkbatchesexport
=> Bulk  Transfer and Get Batches, batch details and batch summary api integration 

src/app/payment-hub/request-to-pay/bulk-batch-export/bulk-batch-export.component.html
* The `tranasactionId` field for batch details was not populating in UI.
=> Fix for transactionId field in batch export

src/app/core/route/route.service.ts
After successful login, Now able to redirect to the homepage without refreshing. Earlier page remain stuck on the same login page until refreshed.
=> Fix: Reload issue after login

src/assets/configuration.properties, src/environments/environment.kubernetes.ts, src/environments/environment.prod.ts, src/environments/environment.ts
* Describe the changes made and why they were made.
* Add a link to teh design document or include the design bullet points related to this PR here.
=> Change default tenant to 'phdefault'

Dockerfile, nginx.conf
- Change the default running image to AmazonLinux
- Run nginx without root permission
- Add file based and standard output access and error logging
=> Improve the OS-level security

.circleci/config.yml
(https://mifosforge.jira.com/browse/GOV-527) Description
* Added CircleCI to build and push docker image to Docker hub
* Add a link to the design document or include the design bullet points related to this PR here.
=> #GOV-527 Build and Push Docker Image to Docker-Hub

.circleci/config.yml
(https://mifosforge.jira.com/browse/GOV-527) Description
* removed gradle command from build step.
* Add a link to the design document or include the design bullet points related to this PR here.
=> #GOV-527 Docker image build

Dockerfile, README.md, docker-compose.yml, package.json
Minor changes in the `docker` files to be able to build and run the web app using `docker` and `docker compose` tools
Plus the `README.md` file was updated with the right instructions to run the application, locally with `ng serve` command or using docker 
- docker compose build and run output messages
- docker container image 
=> Fix to run the app using docker and docker compose

Dockerfile, README.md, package.json
Fix for the node application build process due differences in some libraries versions
=> Fix for the node application build process

package.json, src/app/account-mapper/account-mapper/account-mapper.component.html, src/app/core/authentication/authentication.interceptor.ts, src/app/core/authentication/guard/authentication.guard.ts, src/app/core/shell/content/content.component.html, src/app/core/shell/content/content.component.scss, src/app/directives/directives.module.ts, src/app/directives/file-drag-ndrop/file-drag-ndrop.directive.spec.ts, src/app/directives/file-drag-ndrop/file-drag-ndrop.directive.ts, src/app/directives/has-role/has-role.directive.ts, src/app/home/home-routing.module.ts, src/app/payment-hub/batches/batches.component.html, src/app/payment-hub/batches/batches.component.scss, src/app/payment-hub/batches/batches.component.ts, src/app/payment-hub/paymenthub-routing.module.ts, src/app/payment-hub/sub-batches/sub-batches.component.html, src/app/payment-hub/sub-batches/sub-batches.component.ts, src/app/payment-hub/sub-batches/sub-batches.service.ts, src/app/payment-hub/transfers/transfers.component.html, src/app/shared/shared.module.ts, src/app/vouchers/models/vouchers-model.ts, src/app/vouchers/services/vouchers.service.ts, src/app/vouchers/voucher-management/voucher-management.component.html, src/app/vouchers/voucher-management/voucher-management.component.scss, src/app/vouchers/voucher-management/voucher-management.component.ts, src/app/vouchers/vouchers-bulk-import/vouchers-bulk-import.component.html, src/app/vouchers/vouchers-bulk-import/vouchers-bulk-import.component.scss, src/app/vouchers/vouchers-bulk-import/vouchers-bulk-import.component.ts
Voucher management for creating voucher
=> Voucher management for creating voucher

.circleci/config.yml
[PHEE-551 Get Operations-web up and running](https://fynarfin.atlassian.net/browse/PHEE-551?atlOrigin=eyJpIjoiY2MxMjJiMjdjZDBmNDZlMmE1MGE3NzhlYjYwMmE2MGUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-551] Get Operations-web up and running

src/app/home/home.component.ts, src/app/payment-hub/filter-selector/filter-selector.component.ts, src/app/payment-hub/filter-selector/section-model.ts, src/app/payment-hub/sub-batches/sub-batches.component.ts, src/app/payment-hub/transfers/model/transfer.model.ts, src/app/payment-hub/transfers/transfers.component.html, src/app/payment-hub/transfers/transfers.component.ts, src/app/shared/list-item/list-item.component.html, src/app/shared/list-item/list-item.component.scss, src/app/vouchers/vouchers-section-filter/vouchers-section-filter.component.ts
[GOV-570] Batch, SubBatches and Transfers flow
https://github.com/openMF/ph-ee-operations-web/assets/154766431/2e1b3385-2ec0-42e5-b2ad-68ea82e38767
[GOV-570]: https://mifosforge.jira.com/browse/GOV-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GOV-570] Batch, SubBatches and Transfers flow - part 2
